import RegisterForm from "@/components/auth/RegisterForm";
import styles from "@/styles/LoginPage.module.css";
import { NextPage } from "next";
import Head from "next/head";

const RegisterPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cloud Drive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.wrapper}`}>
        <RegisterForm />
      </div>
    </>
  );
};

export default RegisterPage;
